Algoritmo "utilizaDiv"
// Disciplina   : Lógica de Programação
// Professor   : Jailson Costa dos Santos 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/09/2025
Var
// Seção de Declarações das variáveis 
numero, resposta: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
numero <- 10
resposta <- numero div 3

Escreval(resposta)

Fimalgoritmo